version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./app/static:/app/app/static
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/documentosdb?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: